from __future__ import annotations

import os
import secrets
import stat
import tempfile
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"
MAX_ENV_BYTES = 128 * 1024


def _assignments(content: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        if key and key.replace("_", "").isalnum():
            values[key] = value
    return values


def _secret() -> str:
    return secrets.token_urlsafe(32)


def main() -> None:
    if ENV_PATH.is_symlink():
        raise RuntimeError("refusing to update a symlinked .env")
    if ENV_PATH.exists():
        metadata = ENV_PATH.stat()
        if not stat.S_ISREG(metadata.st_mode) or metadata.st_size > MAX_ENV_BYTES:
            raise RuntimeError(".env must be a bounded regular file")
        content = ENV_PATH.read_text(encoding="utf-8")
    else:
        content = "# Local-only environment generated by make init-env. Never commit this file.\n"
    values = _assignments(content)
    existing_seed_password = values.get("MICROLENS_SEED_PASSWORD")
    if existing_seed_password is not None and len(existing_seed_password) < 12:
        raise RuntimeError("existing MICROLENS_SEED_PASSWORD must contain at least 12 characters")

    postgres_password = values.get("POSTGRES_PASSWORD") or _secret()
    postgres_user = values.get("POSTGRES_USER") or "microlens_app"
    postgres_db = values.get("POSTGRES_DB") or "microlens"
    web_port = values.get("WEB_PORT") or "5173"
    defaults = {
        "COMPOSE_PROJECT_NAME": "microlens-mvp",
        "WEB_PORT": web_port,
        "API_PORT": "8000",
        "APP_ENV": "development",
        "WEB_ORIGIN": f"http://localhost:{web_port}",
        "POSTGRES_DB": postgres_db,
        "POSTGRES_USER": postgres_user,
        "POSTGRES_PASSWORD": postgres_password,
        "DATABASE_URL": (
            "postgresql+psycopg://"
            f"{quote(postgres_user, safe='')}:{quote(postgres_password, safe='')}"
            f"@db:5432/{quote(postgres_db, safe='')}"
        ),
        "REDIS_URL": "redis://redis:6379/0",
        "JWT_SECRET": _secret(),
        "PUBLISH_TOKEN": _secret(),
        "MICROLENS_SEED_PASSWORD": _secret(),
        "COOKIE_SECURE": "false",
        "COOKIE_SAMESITE": "lax",
        "COOKIE_DOMAIN": "",
        "SESSION_LIFETIME_SECONDS": "28800",
        "REGISTRATION_RATE_LIMIT": "5",
        "REGISTRATION_RATE_WINDOW_SECONDS": "300",
        "WORKER_REQUIRE_TRAINING_HANDLER": "false",
    }
    missing = [(key, value) for key, value in defaults.items() if key not in values]
    if missing:
        separator = "" if not content or content.endswith("\n") else "\n"
        addition = "# Added by make init-env; existing values above were preserved.\n"
        addition += "".join(f"{key}={value}\n" for key, value in missing)
        updated = f"{content}{separator}{addition}"
        descriptor, temporary_name = tempfile.mkstemp(prefix=".env.", dir=ROOT, text=True)
        temporary = Path(temporary_name)
        try:
            os.fchmod(descriptor, 0o600)
            with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
                handle.write(updated)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, ENV_PATH)
        finally:
            if temporary.exists():
                temporary.unlink()
    elif ENV_PATH.exists():
        ENV_PATH.chmod(0o600)
    print(f"env_init=PASS added_keys={len(missing)} path=.env")


if __name__ == "__main__":
    main()
